title: Debanjana Kundu
description: ...learning to turn coffee into theorems <br/> <br/>Email <a href="mailto:dkundu@math.toronto.edu">dkundu[at]math[dot]toronto[dot]edu</a><br/><emph>Travel Calendar</emph><br/><iframe src="https://calendar.google.com/calendar/embed?height=300&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FToronto&amp;src=djJlcnVraWNtaTVncjIyNzBzNGx2MThuMnNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%23A87070&amp;showTitle=0&amp;showPrint=0&amp;showCalendars=0" style="border-width:0" width="300" height="300" frameborder="0" scrolling="no"></iframe>
logo: main_image.jpg
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
