title: Debanjana Kundu
description: ...learning to turn coffee into theorems <br/> <br/>Email <a href="mailto:debanjana.kundu@uregina.ca">debanjana.kundu[at]uregina[dot]ca</a><br/>
logo: main_image.jpg
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
