title: Debanjana Kundu
description: ...learning to turn coffee into theorems <br/> <br/>Email <a href="mailto:dkundu@math.ubc.ca">dkundu[at]math[dot]ubc[dot]ca</a><br/>
logo: main_image.jpg
theme: minimal
github:
  is_project_page: false
  is_user_page: false
